[extension]
name = "pgbase62"
extension_name = "base62"
version = "0.0.1"
repository = "https://github.com/adjust/pg-base62"
license = "MIT"
description = "base62 encoding and decoding"
homepage = "https://github.com/adjust/pg-base62"
documentation = "https://github.com/adjust/pg-base62"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = """
    cd pg-base62 && make install
    set -x
    mv /usr/local/pgsql/share/extension/* /usr/share/postgresql/15/extension
    mv /usr/local/pgsql/lib/* /usr/lib/postgresql/15/lib
    """
