[extension]
name = "ip4r"
version = "2.4.2"
repository = "https://github.com/RhodiumToad/ip4r"
license = "PostgreSQL"
description = "IPv4/v6 and IPv4/v6 range index type for PostgreSQL."
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C ip4r install"
