[extension]
name = "ip4r"
version = "2.4.0"
repository = "https://github.com/RhodiumToad/ip4r"
license = "PostgreSQL"
description = "IPv4/v6 and IPv4/v6 range index type for PostgreSQL."
categories = ["data_transformations"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "cd ip4r && make install"
