[extension]
name = "address_standardizer_data_us"
version = "3.3.3"
repository = "https://github.com/postgis/postgis"
license = "GPL-2.0"
description = "The packaged extension address_standardizer_data_us contains data for standardizing US addresses."
homepage = "http://postgis.net/"
documentation = "https://postgis.net/docs/Extras.html"
categories = ["data_transformations"]

[dependencies]
apt = [libc6, libpcre2-8-0]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = """
    cd postgis-3.3.3/extensions/address_standardizer && make install
    set -x
    find /usr/share/postgresql/15/extension -type f -iname '*standardizer--*' -exec rm {} +
    find /usr/share/postgresql/15/extension -type f -iname '*standardizer.*' -exec rm {} +
"""
