[extension]
name = "pgbouncer_fdw"
version = "1.2.0"
repository = "https://github.com/CrunchyData/pgbouncer_fdw"
license = "PostgreSQL"
description = "PostgreSQL Foreign Data Wrapper to Connect to pgbouncer."
homepage = "https://www.crunchydata.com/"
documentation = "https://access.crunchydata.com/documentation/pgbouncer_fdw/latest/"
categories = ["connectors"]

[build]
postgres_version = "17"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = "make -C pgbouncer_fdw install"
