[extension]
name = "pg_semver"
version = "0.32.0"
repository = "https://github.com/theory/pg-semver"
license = "PostgreSQL"
description = "A semantic version data type for PostgreSQL."
documentation = "https://github.com/theory/pg-semver"
categories = ["data_transformations"]

[dependencies]
apt = ["libc6"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = """
    cd pg-semver && make install
    set -x
    mv /usr/local/pgsql/share/extension/* /usr/share/postgresql/15/extension
    mv /usr/local/pgsql/lib/* /usr/lib/postgresql/15/lib
    """

